#!/usr/bin/env bash
set -euo pipefail

OUT_DIR="${1:-./collection-output}"
TS="$(date -u +%Y%m%dT%H%M%SZ)"
RUN_DIR="${OUT_DIR%/}/run-${TS}"

mkdir -p "${RUN_DIR}"

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || {
    echo "Missing required command: $1" >&2
    exit 1
  }
}

require_cmd adb

adb start-server >/dev/null
adb wait-for-device

adb shell getprop > "${RUN_DIR}/getprop.raw.txt" || true

# Keep non-secret lines only.
grep -Evi 'serial|imei|meid|imsi|iccid|mac|wlan[.]mac|bluetooth[.]address|subscriber|msisdn|line1number' \
  "${RUN_DIR}/getprop.raw.txt" > "${RUN_DIR}/getprop.safe.txt" || true

collect() {
  local name="$1"
  local cmd="$2"
  adb shell "$cmd" > "${RUN_DIR}/${name}.txt" 2>&1 || true
}

collect "build_fingerprint" 'getprop ro.build.fingerprint'
collect "kernel_uname" 'uname -a'
collect "cpuinfo" 'cat /proc/cpuinfo'
collect "cmdline" 'cat /proc/cmdline'
collect "mounts" 'cat /proc/mounts'
collect "fstab_candidates" 'ls -l /fstab* /vendor/etc/fstab* /odm/etc/fstab* 2>/dev/null'
collect "partitions_proc" 'cat /proc/partitions'
collect "by_name_links" 'ls -l /dev/block/by-name /dev/block/platform/*/by-name 2>/dev/null'
collect "lsblk" 'lsblk 2>/dev/null'
collect "dmesg_tail" 'dmesg 2>/dev/null | tail -n 400'
collect "input_devices" 'cat /proc/bus/input/devices'
collect "display_service" 'dumpsys display 2>/dev/null'
collect "surfaceflinger" 'dumpsys SurfaceFlinger 2>/dev/null'
collect "audio_policy" 'dumpsys audio 2>/dev/null'
collect "camera_service" 'dumpsys media.camera 2>/dev/null'
collect "wifi_service" 'dumpsys wifi 2>/dev/null'
collect "telephony_registry" 'dumpsys telephony.registry 2>/dev/null'
collect "ril_service_list" 'service list | grep -Ei "ril|radio|telephony"'
collect "packages" 'pm list packages -f'
collect "df" 'df -h'
collect "boot_props" 'getprop | grep -Ei "boot|slot|verity|avb"'
collect "sepolicy" 'getenforce; cat /sys/fs/selinux/policyvers 2>/dev/null'
collect "kernel_config_gz" 'cat /proc/config.gz 2>/dev/null | wc -c'

if adb shell 'test -r /proc/config.gz'; then
  adb pull /proc/config.gz "${RUN_DIR}/config.gz" >/dev/null 2>&1 || true
fi

cat > "${RUN_DIR}/README.txt" <<EOT
Generated by collect_adb_info.sh at ${TS} UTC
Collection scope: read-only diagnostic metadata
Sensitive fields filtered from getprop.safe.txt by keyword deny-list
EOT

echo "Collection complete: ${RUN_DIR}"
